name: Terraform

on:
  push:
    branches:
      - main

env:
  ARM_CLIENT_ID: "740ef847-361c-4fb3-b399-dec204ffaf03"
  ARM_CLIENT_SECRET: "6b781279-3886-41c1-986f-9acf4daa5d44"
  ARM_SUBSCRIPTION_ID: "1edc0a9c-9cf4-40a0-8850-520368179941"
  ARM_TENANT_ID: "b717a219-dd33-4bbd-b14c-24089bf8b8d6"
  TF_WORKING_DIR: './environments/dev'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./environment/dev
        env:
          TF_LOG: DEBUG

      - name: Terraform validate
        run: terraform validate
        working-directory: ./environment/dev
        env:
          TF_LOG: DEBUG
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./environment/dev
        env:
          TF_LOG: DEBUG

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./environment/dev
        env:
          TF_LOG: DEBUG